--BD Postegrsql
CREATE TABLE tbl_Usuario(
Id_Usuario int not null GENERATED BY DEFAULT AS IDENTITY, --Auto Incremento
Usuario VARCHAR(255) NOT NULL,
Senha VARCHAR(255)NOT NULL,
Situacao VARCHAR(255) NOT NULL
);

ALTER TABLE tbl_Usuario ADD CONSTRAINT PK_Usuario PRIMARY KEY(Id_Usuario);