--BD Postegrsql
CREATE TABLE tbl_Hospede(
Id_Hospede int NOT NULL GENERATED BY DEFAULT AS IDENTITY, --Auto Incremento
Nome varchar(255) NOT NULL ,
Dt_Nascimento varchar(255) NOT NULL,
Rg varchar(255),
Cpf varchar(255) NOT NULL,
Passaporte varchar(255) NOT NULL,
Rua varchar(255),
Numero varchar(255),
Bairro varchar(255),
Cidade varchar(255),
Cep varchar(255),
Telefone varchar(255),
Celular_um varchar(255),
Celular_dois varchar(255),
Email varchar(255),
Observacao varchar(255),
Situacao VARCHAR(255) NOT NULL,
Autor INT NOT NULL
);

ALTER TABLE tbl_Hospede ADD CONSTRAINT PK_Hospede PRIMARY KEY (Id_Hospede);
ALTER TABLE tbl_Hospede ADD CONSTRAINT Uni_Documento UNIQUE (Cpf,Passaporte);
ALTER TABLE tbl_Hospede ADD CONSTRAINT FK_Usuario FOREIGN KEY (Autor) REFERENCES tbl_Usuario(id_usuario);