--BD Postegrsql
CREATE TABLE tbl_Reserva(
Num_Reserva INT NOT NULL GENERATED BY DEFAULT AS IDENTITY, --Auto Incremento
Dt_Checkin DATE NOT NULL,
Dt_Checkout DATE NOT NULL,
Quarto_Numero VARCHAR(255) NOT NULL,
Id_Hospede INT NOT null,
ValorTotal NUMERIC NOT null,
Status_Reserva VARCHAR(255) NOT NULL,
Autor INT NOT NULL
);

ALTER TABLE tbl_Reserva ADD CONSTRAINT PK_Reserva PRIMARY KEY (Num_Reserva);
ALTER TABLE tbl_Reserva ADD CONSTRAINT FK_IdHospede FOREIGN KEY (Id_Hospede) REFERENCES tbl_Hospede (Id_Hospede);
ALTER TABLE tbl_Reserva ADD CONSTRAINT FK_NumQuarto FOREIGN KEY (Quarto_Numero) REFERENCES tbl_Quarto(Numero);
ALTER TABLE tbl_Reserva ADD CONSTRAINT FK_Usuario FOREIGN KEY (Autor) REFERENCES tbl_Usuario(id_usuario);